<Project>
  <PropertyGroup>
    <LLVMInstallDir>$(CLANG_PATH)</LLVMInstallDir>
    <LLVMToolsVersion>21.0.0</LLVMToolsVersion>
    <UseMultiToolTask>true</UseMultiToolTask>
    <EnforceProcessCountAcrossBuilds>true</EnforceProcessCountAcrossBuilds>
    <EnableClangTidyCodeAnalysis>false</EnableClangTidyCodeAnalysis>
  </PropertyGroup>
</Project>